export const skillsList = [
  'дизайн',
  'английский',
  'front end',
  'Word',
  'Excel',
  'Access',
  'Corel DRAW',
  'Math CAD',
  'Auto CAD',
  'MatLab',
  'Acrobat Reader',
  'Linus',
  'Sjlaris',
  'MS SQL Server',
  'Oracle',
  'DB/2',
  'MySQL',
  'Windows NT (TCP/IP)',
  'Novell Netware (IPX/SPX)',
  'Unix (TCP/IP)',
  'IIS',
  'Apache',
  'MS Project',
  'Rational Rose',
  'UML',
  'MS Visio',
  'Web Load',
  'Application Center Test (ACT)',
  'Silk Test',
  'Silk Performer',
  'NUnit',
  'JUnit',
  "M'S Exchange Server",
  ' Visual C++',
  'MFC',
  'Win32 API',
  'OLE',
  'STL',
  'ATL',
  'DCOM',
  'COM',
  'COM+',
  'MTS',
  'ActiveX',
  'ODBC',
  'ADO',
  'OLE DB',
  'VSS',
  'Visual Basic',
  'VBA',
  'HTML',
  'XML/XSL',
  'UML',
  'SQL',
  'C/C++',
  'ASP',
  'Java Script',
  'CORB',
  'PHP',
  'Pascal',
  'Delphi',
  'Java',
  'JSP Serviets JTS',
  'JMS',
  'Struts Framework',
  'Hibernate',
  'JSF',
  'JAAS',
  'JNDI',
  'JWS',
  'JAXP',
  'EJB',
  'Ant',
  'Log4J',
  'Basic Java packages (AWT, SWING, etc.)',
  'Threads',
  'JDBC',
  'RMI',
  'Java Application Servers JBoss',
  'WebLogic',
  'WebSphere',
  'Tomcat',
  '.NET ',
  'С#',
  'VB.NET',
  'Managed C++',
  ' J#',
  '.Net Framework',
  'ADO.NET',
  'ASP.NET',
  '.Net Security',
  '.Net Cryptography',
  'WSE 2.0',
  'Net Remoting',
  'Com to Net interop',
  'Net to Com interop',
  'ServicedComponents (COM+ на NET)',
  'Windows Forms',
  'GDI+',
  'Photoshop',
  'CorelDRAW',
  'OpenGL',
  'DirectX',
  'Proxy',
  'FireWall',
];
